### ISSUE TITLE
php version (8.2.2) does not satisfy that requirement

### ISSUE THREAD

**Issue by kilvn** [laminas/laminas-httphandlerrunner#38]
```shell
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-httphandlerrunner 1.2.0 requires php ^7.1 -> your php version (8.2.2) does not satisfy that requirement.
    - laminas/laminas-httphandlerrunner[1.3.0, ..., 1.4.0] require php ^7.3 || ~8.0.0 -> your php version (8.2.2) does not satisfy that requirement.
    - laminas/laminas-httphandlerrunner 1.5.0 requires php ^7.3 || ~8.0.0 || ~8.1.0 -> your php version (8.2.2) does not satisfy that requirement.
    - flarum/core v1.6.3 requires laminas/laminas-httphandlerrunner ^1.2.0 -> satisfiable by laminas/laminas-httphandlerrunner[1.2.0, 1.3.0, 1.4.0, 1.5.0].
    - Root composer.json requires flarum/core ^1.6 -> satisfiable by flarum/core[v1.6.0, v1.6.1, v1.6.2, v1.6.3].
```

**Comment by kilvn** [comment]
When I use php 8.2.2 to install flash/core v1.6.3, an exception is thrown. The laminas/laminas httphandlerrunner package restricts the php version and makes me unable to install it.

**Comment by Ocramius** [comment]
You will need at least version `2.3.0`, which introduced PHP 8.2 support.

**Comment by froschdesign** [comment]
@kilvn 
laminas-httphandlerrunner allows version 8.2 of PHP since 10 October 2022, long before the official release of 8.2 (8 Dec 2022).

The problem here is the package flarum-core because it only allows version 1.x of laminas-httphandlerrunner:

https://github.com/flarum/flarum-core/blob/a4b54e521a7b4c3e27cf54f01e412240c9a6f80f/composer.json#L64

It looks like you have to report the problem at this repository: https://github.com/flarum/framework

Here can you find a related discussion in their forum: https://discuss.flarum.org/d/32225-getting-error-on-php-82

**Comment by kilvn** [comment]
> @kilvn laminas-httphandlerrunner allows version 8.2 of PHP since 10 October 2022, long before the official release of 8.2 (8 Dec 2022).
> 
> The problem here is the package flarum-core because it only allows version 1.x of laminas-httphandlerrunner:
> 
> https://github.com/flarum/flarum-core/blob/a4b54e521a7b4c3e27cf54f01e412240c9a6f80f/composer.json#L64
> 
> It looks like you have to report the problem at this repository: https://github.com/flarum/framework
> 
> Here can you find a related discussion in their forum: https://discuss.flarum.org/d/32225-getting-error-on-php-82

Well, thank you very much.
